version: 2
sources:
    - name: source
      database: SCD2_DB
      schema: BRONZE
      tables:
        - name: WORK_PRODUCT_COPY
    
    - name: xfm
      database: SCD2_DB
      schema: SILVER
      tables:
        - name: WORK_PRODUCT_TRANSFORM